### ISSUE TITLE
AesonQQ doesn't parse empty object {}

### ISSUE THREAD

**Issue by coco98** [sol/aeson-qq#11]
Hi,

Building on the README example:

This doesn't work:
`let john = [aesonQQ| {age: 23, name: "John", likes: {} } |]`
giving out:
`Exception when trying to run compile-time code:
      Error in aesonExp: "txt" (line 1, column 36):
unexpected "}"
expecting space or ":"`

These work:

```
[aesonQQ| {age: 23, name: "John", likes: []} |]
[aesonQQ| {age: 23, name: "John", likes: null} |]
```

**Comment by supki** [comment]
It's still possible to break the parser by inserting spaces between `{}`, e.g.

```haskell
>>> import Data.Aeson.QQ
>>> :set -XQuasiQuotes 
>>> [aesonQQ|{"foo": {}}|]
Object (fromList [("foo",Object (fromList []))])
>>> [aesonQQ|{"foo": { }}|]

<interactive>:11:1:
    Exception when trying to run compile-time code:
      Error in aesonExp: "txt" (line 1, column 11):
unexpected "}"
expecting space, "$" or "\""
    Code: Language.Haskell.TH.Quote.quoteExp aesonQQ "{\"foo\": { }}"
```
